name: mafia
description: "Mafia Vs Citizen."

publisher: 'Mohammad Haddadian'


version: 2.1.3+11

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  permission_handler: ^11.3.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1
  livekit_client: ^2.0.2
  either_dart: ^1.0.0
  loading_animation_widget: ^1.2.1
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.1
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  dio: ^5.4.1
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.5
  lottie: ^3.1.0
  vibration: ^1.8.4
  audioplayers: ^5.2.1
  circular_countdown_timer: ^0.2.3
  bot_toast: ^4.1.3
  flutter_snake_navigationbar: ^0.6.1
  share_plus: ^7.2.2
  pretty_dio_logger: ^1.3.1
  wakelock_plus: ^1.1.4
  slide_countdown: ^1.5.2
  animate_do: ^3.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  firebase_analytics: ^10.8.6
  firebase_crashlytics: ^3.4.16
  flutter_reorderable_grid_view: ^4.0.0
  flutter_expandable_fab: ^2.0.0
  flutter_volume_controller: ^1.3.1
  gif: ^2.3.0
  easy_refresh: ^3.4.0
  font_awesome_flutter: ^10.7.0
  flutter_pannable_rating_bar: ^2.7.2+1
  myket_iap: ^1.1.5
  card_swiper: ^3.0.1
  flutter_card_swiper: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_launcher_icon.png"
  min_sdk_android: 23

flutter_native_splash:
  android_12:
  web: false

flutter:

  
  uses-material-design: true

  
  assets:
    - images/
    - assets/
  
  fonts:
    - family: shabnam
      fonts:
        - asset: font/shabnam.ttf
    - family: shohre
      fonts:
        - asset: font/shohre.ttf
  
